/**
 * StyleSheet definitions for the UCF mobile-native app.
 * Extracted from App.tsx monolith — see App.tsx header comment for details.
 */

import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#090909",
  },
  fontLoadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#090909",
  },
  bgImage: {
    flex: 1,
  },
  bgImageStyle: {
    opacity: 0.28,
  },
  bgOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(8,8,8,0.9)",
  },
  bugsOverlayWrap: {
    position: "absolute",
    left: 10,
    bottom: 92,
    zIndex: 3,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  bugsImage: {
    width: 82,
    height: 72,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#44403c",
  },
  bugsQuoteBox: {
    backgroundColor: "rgba(24,24,24,0.92)",
    borderWidth: 1,
    borderColor: "#44403c",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    maxWidth: 168,
    marginBottom: 8,
  },
  bugsQuoteText: {
    color: "#d6d3d1",
    fontSize: 10,
    lineHeight: 12,
    textTransform: "uppercase",
  },
  screen: {
    flex: 1,
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: "#292524",
    backgroundColor: "rgba(9,9,9,0.92)",
    paddingHorizontal: 12,
    paddingTop: 0,
    paddingBottom: 10,
    gap: 6,
    alignItems: "center",
  },
  headerTitleWrap: {
    width: "100%",
    alignItems: "center",
    paddingHorizontal: 8,
    overflow: "visible",
  },
  title: {
    width: "94%",
    fontSize: 32,
    lineHeight: 36,
    color: "#f59e0b",
    letterSpacing: 1.1,
    fontFamily: "MostWazted",
    textAlign: "center",
    textTransform: "uppercase",
    includeFontPadding: false,
    paddingHorizontal: 0,
    paddingBottom: 1,
    maxWidth: "94%",
    flexShrink: 1,
    textShadowColor: "rgba(217, 119, 6, 0.8)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  subTitle: {
    marginTop: 2,
    color: "#78716c",
    fontSize: 9,
    letterSpacing: 0.6,
    textAlign: "center",
  },
  headerRight: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    rowGap: 6,
    columnGap: 8,
    width: "100%",
  },
  headerUtilityGroup: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minWidth: 0,
  },
  headerWalletSlot: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 0,
    gap: 6,
  },
  headerSetupBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  headerSetupBadgeReady: {
    borderColor: "#166534",
    backgroundColor: "rgba(22, 163, 74, 0.18)",
  },
  headerSetupBadgeWarn: {
    borderColor: "#a16207",
    backgroundColor: "rgba(217, 119, 6, 0.16)",
  },
  headerSetupBadgePending: {
    borderColor: "#44403c",
    backgroundColor: "rgba(41, 37, 36, 0.8)",
  },
  headerSetupBadgeText: {
    color: "#e7e5e4",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  headerGearSlot: {
    width: 34,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  soundControlsWrap: {
    position: "relative",
    zIndex: 10,
  },
  soundGearBtn: {
    borderWidth: 1,
    borderColor: "#3f3f46",
    backgroundColor: "#111111",
    borderRadius: 9,
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  soundGearGlyph: {
    color: "#d6d3d1",
    fontSize: 18,
    lineHeight: 18,
    fontWeight: "800",
  },
  soundGearGlyphOpen: {
    color: "#f59e0b",
  },
  soundGearBtnOpen: {
    borderColor: "#a16207",
    backgroundColor: "rgba(120,53,15,0.32)",
  },
  soundMenu: {
    position: "absolute",
    top: 40,
    right: 0,
    minWidth: 132,
    borderWidth: 1,
    borderColor: "#44403c",
    borderRadius: 10,
    backgroundColor: "rgba(14,14,14,0.97)",
    paddingVertical: 4,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  soundMenuRow: {
    minHeight: 34,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  soundMenuLabel: {
    color: "#d6d3d1",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  soundMenuValue: {
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.7,
  },
  soundMenuValueOn: {
    color: "#f59e0b",
  },
  soundMenuValueOff: {
    color: "#71717a",
  },
  walletHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 1,
    minWidth: 0,
  },
  walletChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#3f3f46",
    backgroundColor: "#111111",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    maxWidth: "100%",
  },
  walletBalanceText: {
    color: "#a8a29e",
    fontSize: 9,
    fontWeight: "700",
  },
  walletChipText: {
    color: "#f59e0b",
    fontSize: 10,
    fontWeight: "700",
    flexShrink: 1,
  },
  walletChipClose: {
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  walletChipCloseText: {
    color: "#78716c",
    fontSize: 10,
    fontWeight: "700",
  },
  connectBtn: {
    backgroundColor: "#d97706",
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  connectBtnText: {
    color: "#111111",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  topStatsRow: {
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 6,
  },
  statTile: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#292524",
    backgroundColor: "rgba(17,17,17,0.9)",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  statTileLabel: {
    fontSize: 9,
    color: "#78716c",
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  statTileValue: {
    marginTop: 2,
    color: "#fbbf24",
    fontSize: 14,
    fontWeight: "800",
  },
  toastLayer: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 84,
    zIndex: 18,
    gap: 8,
    alignItems: "stretch",
  },
  toastCard: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  toastCardInfo: {
    borderColor: "#44403c",
    backgroundColor: "rgba(24,24,27,0.96)",
  },
  toastCardSuccess: {
    borderColor: "#15803d",
    backgroundColor: "rgba(20,83,45,0.94)",
  },
  toastCardError: {
    borderColor: "#b45309",
    backgroundColor: "rgba(120,53,15,0.96)",
  },
  toastLabel: {
    color: "#f5f5f4",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  toastMessage: {
    marginTop: 4,
    color: "#fafaf9",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 16,
  },
  fightOverlayLayer: {
    position: "absolute",
    top: 8,
    left: 0,
    right: 0,
    zIndex: 12,
    gap: 8,
    alignItems: "center",
    paddingHorizontal: 8,
  },
  fightOverlayCard: {
    width: "100%",
    maxWidth: 420,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 9,
    paddingHorizontal: 12,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 10,
  },
  fightOverlayCommentaryCard: {
    borderColor: "#a16207",
    backgroundColor: "rgba(120,53,15,0.9)",
  },
  fightOverlayEliminationCard: {
    borderColor: "#b45309",
    backgroundColor: "rgba(127,29,29,0.92)",
  },
  fightOverlayLabel: {
    color: "#fffbeb",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.9,
    textTransform: "uppercase",
  },
  fightOverlayText: {
    marginTop: 4,
    color: "#fafaf9",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 16,
  },
  contentWrap: {
    flex: 1,
    paddingHorizontal: 10,
  },
  scrollContent: {
    paddingTop: 4,
    paddingBottom: 88,
    gap: 10,
  },
  slotPillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  slotPill: {
    borderWidth: 1,
    borderColor: "#44403c",
    borderRadius: 6,
    backgroundColor: "rgba(24,24,24,0.85)",
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  slotPillActive: {
    borderColor: "#b45309",
    backgroundColor: "rgba(120,53,15,0.35)",
  },
  slotPillText: {
    fontSize: 10,
    fontWeight: "800",
  },
  panel: {
    borderWidth: 1,
    borderColor: "#44403c",
    borderRadius: 12,
    backgroundColor: "rgba(14,14,14,0.95)",
    padding: 10,
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.32,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  panelTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  panelToggleRow: {
    borderRadius: 8,
    paddingVertical: 2,
  },
  panelLabel: {
    color: "#78716c",
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontWeight: "700",
  },
  panelState: {
    fontSize: 10,
    fontWeight: "800",
  },
  panelMeta: {
    color: "#71717a",
    fontSize: 10,
    fontWeight: "700",
  },
  panelMetaGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  panelCollapseText: {
    color: "#a16207",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  panelTitle: {
    color: "#f5f5f4",
    fontSize: 27,
    lineHeight: 31,
    letterSpacing: 1.3,
    fontFamily: "MostWazted",
    textShadowColor: "rgba(217, 119, 6, 0.6)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  panelMuted: {
    color: "#a8a29e",
    fontSize: 12,
  },
  arenaStatusStrip: {
    marginTop: 6,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#292524",
    backgroundColor: "rgba(17,17,17,0.9)",
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 9,
  },
  arenaStatusText: {
    color: "#d6d3d1",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.7,
  },
  arenaTimerStrip: {
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#44403c",
    backgroundColor: "#0f0f0f",
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 9,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  arenaTimerLabel: {
    color: "#a8a29e",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.6,
    flex: 1,
  },
  arenaTimerValue: {
    color: "#f59e0b",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.9,
  },
  panelFootnote: {
    color: "#78716c",
    fontSize: 10,
    textAlign: "center",
    marginTop: 2,
  },
  idleArenaWrap: {
    borderWidth: 1,
    borderColor: "#292524",
    borderRadius: 8,
    overflow: "hidden",
    position: "relative",
    height: 260,
  },
  idleArenaImage: {
    width: "100%",
    height: "100%",
  },
  idleArenaShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(10,10,10,0.65)",
  },
  idleCageImage: {
    position: "absolute",
    right: 0,
    left: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
    opacity: 0.55,
  },
  idleArenaTextWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 14,
    alignItems: "center",
    paddingHorizontal: 14,
    gap: 4,
  },
  idleArenaTitle: {
    color: "#f59e0b",
    fontSize: 24,
    letterSpacing: 1.2,
    textAlign: "center",
    fontFamily: "MostWazted",
    textShadowColor: "rgba(217, 119, 6, 0.7)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  idleArenaSub: {
    color: "#d6d3d1",
    fontSize: 13,
    textAlign: "center",
  },
  idleArenaHint: {
    color: "#a8a29e",
    fontSize: 10,
    textAlign: "center",
    letterSpacing: 0.8,
  },
  idleArtRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  idleArtThumb: {
    flex: 1,
    height: 100,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#3f3f46",
    resizeMode: "cover",
  },
  sectionLabel: {
    color: "#a8a29e",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 2,
  },
  listStack: {
    gap: 6,
  },
  rowCard: {
    borderWidth: 1,
    borderColor: "#3f3f46",
    borderRadius: 8,
    backgroundColor: "rgba(20,20,20,0.94)",
    paddingVertical: 7,
    paddingHorizontal: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  rowCardTall: {
    borderWidth: 1,
    borderColor: "#3f3f46",
    borderRadius: 8,
    backgroundColor: "rgba(20,20,20,0.94)",
    paddingVertical: 8,
    paddingHorizontal: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  rowCardEliminated: {
    borderColor: "#52525b",
    backgroundColor: "rgba(39,39,42,0.72)",
  },
  rowIdx: {
    width: 18,
    color: "#78716c",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
  },
  rowMain: {
    flex: 1,
    gap: 2,
  },
  rowTopLine: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  rowName: {
    color: "#f5f5f4",
    fontSize: 12,
    fontWeight: "700",
    flex: 1,
  },
  rowNameEliminated: {
    color: "#9ca3af",
  },
  rowSub: {
    color: "#71717a",
    fontSize: 10,
  },
  rowSubEliminated: {
    color: "#6b7280",
  },
  rowSubStrong: {
    color: "#22d3ee",
    fontSize: 10,
    fontWeight: "700",
  },
  rowMeta: {
    color: "#a8a29e",
    fontSize: 10,
    fontWeight: "700",
  },
  avatarWrap: {
    width: 40,
    height: 40,
    borderRadius: 6,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#3f3f46",
    backgroundColor: "#18181b",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  avatarImageEliminated: {
    opacity: 0.36,
  },
  avatarFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarFallbackText: {
    color: "#78716c",
    fontSize: 9,
    fontWeight: "700",
  },
  myBetTag: {
    color: "#22d3ee",
    fontSize: 8,
    fontWeight: "800",
    borderWidth: 1,
    borderColor: "#155e75",
    backgroundColor: "rgba(8,47,73,0.4)",
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 1,
    overflow: "hidden",
  },
  hpTrack: {
    height: 5,
    borderRadius: 3,
    backgroundColor: "#292524",
    overflow: "hidden",
  },
  hpFill: {
    height: "100%",
    backgroundColor: "#22c55e",
  },
  betCard: {
    borderWidth: 1,
    borderColor: "#292524",
    borderRadius: 8,
    backgroundColor: "#131313",
    overflow: "hidden",
  },
  betCardSelected: {
    borderColor: "#b45309",
    backgroundColor: "rgba(120,53,15,0.2)",
  },
  betTileGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  betTile: {
    width: "48.6%",
    borderWidth: 1,
    borderColor: "#3f3f46",
    borderRadius: 10,
    backgroundColor: "rgba(15,15,15,0.92)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.26,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  betTileSelected: {
    borderColor: "#d97706",
    backgroundColor: "rgba(120,53,15,0.22)",
  },
  betTileTap: {
    padding: 8,
    gap: 6,
  },
  betTileImage: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#44403c",
    backgroundColor: "#111111",
  },
  betTileBody: {
    gap: 2,
  },
  betCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  betCardAvatarWrap: {
    width: 46,
    height: 46,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#3f3f46",
    overflow: "hidden",
    backgroundColor: "#18181b",
  },
  betCardAvatar: {
    width: "100%",
    height: "100%",
  },
  betCardAvatarFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  betCardInfo: {
    flex: 1,
    gap: 2,
  },
  betSelectLabel: {
    color: "#f59e0b",
    fontSize: 9,
    fontWeight: "800",
  },
  betControlsWrap: {
    borderTopWidth: 1,
    borderTopColor: "#44403c",
    paddingVertical: 8,
    paddingHorizontal: 8,
    gap: 6,
    backgroundColor: "rgba(8,8,8,0.4)",
  },
  quickAmountRow: {
    flexDirection: "row",
    gap: 6,
  },
  quickAmountBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#44403c",
    borderRadius: 6,
    backgroundColor: "#111111",
    paddingVertical: 6,
    alignItems: "center",
  },
  quickAmountBtnActive: {
    borderColor: "#d97706",
    backgroundColor: "rgba(217,119,6,0.28)",
  },
  quickAmountText: {
    color: "#e7e5e4",
    fontSize: 10,
    fontWeight: "700",
  },
  combatHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  combatPairsStack: {
    gap: 8,
  },
  combatPairRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    borderWidth: 1,
    borderColor: "#292524",
    borderRadius: 8,
    backgroundColor: "rgba(24,24,24,0.9)",
    padding: 8,
  },
  combatFighterCard: {
    flex: 1,
    alignItems: "center",
    gap: 4,
  },
  combatFighterCardEliminated: {
    opacity: 0.88,
  },
  combatAvatar: {
    width: 78,
    height: 78,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#44403c",
    backgroundColor: "#111111",
  },
  combatAvatarEliminated: {
    opacity: 0.34,
    borderColor: "#52525b",
  },
  combatName: {
    color: "#e7e5e4",
    fontSize: 11,
    fontWeight: "700",
  },
  combatNameEliminated: {
    color: "#9ca3af",
  },
  vsText: {
    color: "#d97706",
    fontSize: 24,
    lineHeight: 28,
    fontFamily: "MostWazted",
    letterSpacing: 0,
    minWidth: 34,
    textAlign: "center",
    paddingHorizontal: 2,
    textTransform: "uppercase",
    textShadowColor: "rgba(217, 119, 6, 0.7)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  vsTextDanger: {
    color: "#f87171",
    textShadowColor: "rgba(239, 68, 68, 0.8)",
  },
  vsTextDodge: {
    color: "#4ade80",
    textShadowColor: "rgba(34, 197, 94, 0.7)",
  },
  vsTextGuard: {
    color: "#60a5fa",
    textShadowColor: "rgba(59, 130, 246, 0.8)",
  },
  combatBenchWrap: {
    borderTopWidth: 1,
    borderTopColor: "#292524",
    paddingTop: 8,
    gap: 8,
  },
  turnFeedWrap: {
    borderTopWidth: 1,
    borderTopColor: "#292524",
    paddingTop: 8,
    gap: 8,
  },
  turnFeedCard: {
    borderWidth: 1,
    borderColor: "#44403c",
    borderRadius: 8,
    backgroundColor: "rgba(20,20,20,0.95)",
    paddingVertical: 7,
    paddingHorizontal: 8,
    gap: 4,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  turnFeedTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  turnFeedTitle: {
    color: "#f59e0b",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  turnFeedMeta: {
    color: "#a8a29e",
    fontSize: 10,
    fontWeight: "700",
  },
  turnFeedLine: {
    color: "#d6d3d1",
    fontSize: 10,
  },
  turnFeedPairRow: {
    gap: 3,
  },
  turnFeedMatchupText: {
    color: "#e7e5e4",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 16,
  },
  turnFeedOutcome: {
    color: "#d6d3d1",
    fontSize: 10,
    fontWeight: "600",
    textAlign: "center",
    lineHeight: 14,
  },
  turnFeedOutcomeName: {
    color: "#d6d3d1",
    fontWeight: "700",
  },
  turnFeedOutcomeAction: {
    fontWeight: "800",
  },
  turnFeedOutcomeTrade: {
    color: "#fbbf24",
    fontWeight: "800",
  },
  turnFeedOutcomeCounter: {
    color: "#60a5fa",
    fontWeight: "800",
  },
  turnFeedOutcomeCatch: {
    color: "#c084fc",
    fontWeight: "800",
  },
  turnFeedOutcomeDodge: {
    color: "#4ade80",
    fontSize: 10,
    fontWeight: "800",
    textAlign: "center",
    lineHeight: 14,
  },
  turnFeedOutcomeMuted: {
    color: "#78716c",
    fontSize: 10,
    fontWeight: "600",
    textAlign: "center",
    lineHeight: 14,
  },
  turnFeedHpRow: {
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
  },
  turnFeedHpTrack: {
    flex: 1,
    height: 4,
    borderRadius: 3,
    backgroundColor: "#3f3f46",
    overflow: "hidden",
  },
  turnFeedHpFill: {
    height: "100%",
    backgroundColor: "#22c55e",
  },
  turnFeedHpFillLow: {
    backgroundColor: "#f59e0b",
  },
  turnFeedHpFillElim: {
    backgroundColor: "#6b7280",
  },
  turnFeedHpMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  turnFeedHpMetaText: {
    color: "#a8a29e",
    fontSize: 9,
    fontWeight: "700",
  },
  turnFeedElims: {
    color: "#fca5a5",
    fontSize: 10,
    fontWeight: "700",
  },
  hpBoardWrap: {
    borderTopWidth: 1,
    borderTopColor: "#292524",
    paddingTop: 8,
    gap: 8,
  },
  betAmountRow: {
    flexDirection: "row",
    gap: 6,
  },
  betAmountInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#44403c",
    borderRadius: 6,
    backgroundColor: "#101010",
    color: "#f5f5f4",
    fontSize: 12,
    paddingVertical: 7,
    paddingHorizontal: 10,
  },
  lastSigCard: {
    borderWidth: 1,
    borderColor: "#166534",
    borderRadius: 8,
    backgroundColor: "rgba(6,78,59,0.35)",
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  lastSigText: {
    color: "#86efac",
    fontSize: 10,
    fontWeight: "700",
  },
  deployBtn: {
    borderWidth: 1,
    borderColor: "#b45309",
    borderRadius: 8,
    backgroundColor: "#d97706",
    paddingVertical: 10,
    alignItems: "center",
    marginTop: 2,
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  deployBtnText: {
    color: "#111111",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  emptyText: {
    color: "#78716c",
    fontSize: 12,
  },
  dmgReceived: {
    color: "#ef4444",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 2,
  },
  turnFeedMatchup: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 4,
  },
  turnFeedFighterCol: {
    flex: 1,
    alignItems: "center",
    gap: 1,
  },
  turnFeedFighterName: {
    color: "#d6d3d1",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
  },
  turnFeedDmgReceived: {
    color: "#ef4444",
    fontSize: 12,
    fontWeight: "900",
  },
  combatStartingWrap: {
    marginTop: 4,
  },
  combatStartingText: {
    color: "#f59e0b",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 12,
  },
  rewardGrid: {
    flexDirection: "row",
    gap: 6,
  },
  setupCard: {
    marginTop: 10,
    gap: 8,
  },
  setupModeRow: {
    flexDirection: "row",
    gap: 8,
  },
  setupModeBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#44403c",
    borderRadius: 8,
    backgroundColor: "#111111",
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: "center",
  },
  setupModeBtnActive: {
    borderColor: "#d97706",
    backgroundColor: "rgba(217, 119, 6, 0.18)",
  },
  setupModeBtnText: {
    color: "#a8a29e",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  setupModeBtnTextActive: {
    color: "#fbbf24",
  },
  setupInput: {
    borderWidth: 1,
    borderColor: "#44403c",
    borderRadius: 8,
    backgroundColor: "#101010",
    color: "#f5f5f4",
    fontSize: 12,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  setupTextarea: {
    minHeight: 108,
    textAlignVertical: "top",
  },
  setupTextareaSmall: {
    minHeight: 72,
    textAlignVertical: "top",
  },
  setupSecretLabel: {
    color: "#78716c",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  setupSecretValue: {
    color: "#f5f5f4",
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "700",
  },
  rewardCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#292524",
    borderRadius: 8,
    backgroundColor: "#131313",
    paddingVertical: 8,
    paddingHorizontal: 8,
    gap: 2,
  },
  rewardLabel: {
    color: "#78716c",
    fontSize: 10,
  },
  rewardValueGreen: {
    color: "#4ade80",
    fontSize: 13,
    fontWeight: "800",
  },
  rewardValueAmber: {
    color: "#fbbf24",
    fontSize: 13,
    fontWeight: "800",
  },
  claimBtn: {
    borderWidth: 1,
    borderColor: "#15803d",
    borderRadius: 8,
    backgroundColor: "#16a34a",
    paddingVertical: 8,
    alignItems: "center",
    marginTop: 2,
  },
  claimBtnText: {
    color: "#111111",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  ichorBig: {
    color: "#f59e0b",
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "900",
  },
  ichorBottleImage: {
    width: 96,
    height: 144,
    alignSelf: "center",
    marginTop: 6,
    marginBottom: 4,
  },
  ichorUnit: {
    color: "#a16207",
    fontSize: 10,
    letterSpacing: 0.8,
    fontWeight: "700",
  },
  ichorWarningText: {
    color: "#a16207",
    fontSize: 10,
    textAlign: "center",
  },
  txDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  txDotOk: {
    backgroundColor: "#22c55e",
  },
  txDotErr: {
    backgroundColor: "#ef4444",
  },
  chatMetaWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  chatSlowTag: {
    color: "#a8a29e",
    fontSize: 9,
    fontWeight: "700",
    borderWidth: 1,
    borderColor: "#3f3f46",
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 1,
    overflow: "hidden",
  },
  chatStack: {
    gap: 8,
    maxHeight: 480,
  },
  chatRow: {
    borderWidth: 1,
    borderColor: "#292524",
    borderRadius: 8,
    backgroundColor: "#131313",
    padding: 8,
    gap: 3,
  },
  chatTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  chatUserWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  chatAvatar: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#44403c",
  },
  chatUser: {
    color: "#a8a29e",
    fontSize: 11,
    fontWeight: "700",
  },
  chatUserMine: {
    color: "#f59e0b",
  },
  chatAge: {
    color: "#71717a",
    fontSize: 10,
  },
  eliminatedTag: {
    color: "#fca5a5",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  chatMsg: {
    color: "#e7e5e4",
    fontSize: 12,
    lineHeight: 16,
  },
  chatInputRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 2,
  },
  chatInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#44403c",
    borderRadius: 8,
    backgroundColor: "#101010",
    color: "#f5f5f4",
    fontSize: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  sendBtn: {
    borderRadius: 8,
    backgroundColor: "#d97706",
    paddingHorizontal: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  sendBtnText: {
    color: "#111111",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  errorText: {
    color: "#fbbf24",
    fontSize: 11,
  },
  btnStack: {
    gap: 8,
  },
  actionBtn: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#44403c",
    paddingVertical: 10,
    alignItems: "center",
  },
  actionBtnPrimary: {
    backgroundColor: "#b45309",
  },
  actionBtnDanger: {
    backgroundColor: "#7f1d1d",
  },
  actionBtnText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  statusText: {
    color: "#d6d3d1",
    fontSize: 11,
    fontWeight: "700",
  },
  statusErrorDetail: {
    marginTop: 3,
    color: "#fdba74",
    fontSize: 10,
    lineHeight: 13,
  },
  statusBanner: {
    marginHorizontal: 10,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: "#44403c",
    backgroundColor: "rgba(20,20,20,0.9)",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  statusBannerWarn: {
    marginHorizontal: 10,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: "#b45309",
    backgroundColor: "rgba(120,53,15,0.6)",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  statusBannerMuted: {
    marginHorizontal: 10,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: "#3f3f46",
    backgroundColor: "rgba(24,24,27,0.75)",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  btnDisabled: {
    opacity: 0.55,
  },
  pressablePressed: {
    opacity: 0.84,
    transform: [{ scale: 0.985 }],
  },
  bottomTabs: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    borderTopWidth: 1,
    borderTopColor: "#292524",
    backgroundColor: "rgba(9,9,9,0.96)",
    flexDirection: "row",
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 14,
    gap: 8,
  },
  bottomTabBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#292524",
    borderRadius: 8,
    backgroundColor: "#121212",
    paddingVertical: 9,
    alignItems: "center",
  },
  bottomTabBtnActive: {
    borderColor: "#a16207",
    backgroundColor: "rgba(120,53,15,0.35)",
  },
  bottomTabText: {
    color: "#71717a",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
  },
  bottomTabTextActive: {
    color: "#f59e0b",
  },
  networkToggleRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
    marginTop: 2,
  },
  networkToggleBtn: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#3f3f46",
    backgroundColor: "rgba(24,24,27,0.5)",
    alignItems: "center",
  },
  networkToggleBtnActive: {
    borderColor: "#f59e0b",
    backgroundColor: "rgba(245,158,11,0.12)",
  },
  networkToggleText: {
    color: "#71717a",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  networkToggleTextActive: {
    color: "#f59e0b",
  },
  moveTag: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.6,
    marginTop: 3,
    textAlign: "center",
  },
  turnFeedMoveRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 2,
    marginBottom: 2,
  },
  turnFeedMoveTag: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  turnFeedMoveSep: {
    fontSize: 9,
    color: "#57534e",
    fontWeight: "600",
  },
  winnerOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  winnerOverlayBackdrop: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.75)",
  },
  winnerCard: {
    backgroundColor: "#1c1917",
    borderWidth: 2,
    borderColor: "#f59e0b",
    borderRadius: 20,
    paddingVertical: 28,
    paddingHorizontal: 32,
    alignItems: "center",
    width: "82%",
    maxWidth: 340,
    shadowColor: "#f59e0b",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 24,
    elevation: 20,
  },
  winnerCrown: {
    color: "#f59e0b",
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: 4,
    marginBottom: 2,
  },
  winnerRumbleLabel: {
    color: "#a8a29e",
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 1.5,
    marginBottom: 16,
  },
  winnerAvatarRing: {
    width: 112,
    height: 112,
    borderRadius: 56,
    borderWidth: 3,
    borderColor: "#f59e0b",
    overflow: "hidden",
    marginBottom: 14,
  },
  winnerAvatar: {
    width: "100%",
    height: "100%",
  },
  winnerName: {
    color: "#fafaf9",
    fontSize: 22,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 6,
  },
  winnerStats: {
    color: "#a8a29e",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0.5,
    marginBottom: 14,
  },
  winnerPayoutRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(245,158,11,0.12)",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginBottom: 14,
  },
  winnerPayoutLabel: {
    color: "#a8a29e",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.8,
  },
  winnerPayoutValue: {
    color: "#f59e0b",
    fontSize: 18,
    fontWeight: "800",
  },
  winnerDismissHint: {
    color: "#57534e",
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 1,
  },
});
